### PR TITLE
New connector

### PR DESCRIPTION
**Pull request by samuelsimoes**
This a proposal to a new connector (still wip).

This new connector isn't a simple javascript function in favor of a literal object that has the `createClass` method that return an React.js component with some necessary methods to make the new connection.

This PR also remove the dependency of Fluxo. Every object that you want use to "store layer" that responds to `toJSON` and `on` methods (I'll create a better doc about this) can be connected on the "connected components". You can use Fluxo, Backbone's models, simple javascript objects or whatever you want. If your store layer use some other ways to warn the component that something is updated you can override some connector's methods to adapt to your needs (I'll doc this).

The new usage becomes something like: 

``` jsx
// A normal component, your view layer
PersonComponent = React.createClass({
  childContextTypes: {
    actions: React.PropTypes.object.isRequired
  },

  render: function () {
    return <button onClick={this.context.actions.person.update} />;
  }
});

// The wrapper component that connect the component above to the actions and stores
var PersonComponentConnected = FluxoReactConnectStores.createClass({
  getDefaultProps: {
    return { component: PersonComponent };
  },

  getStores: function () {
    return {
      person: Fluxo.ObjectStore.create(this.props.personInitialData)
    };
  },

  getActions: function () {
    return {
      person: extend({ person: this.stores.person }, PersonActions)
    };
  }
});
```

As you can see the `getStores` and `getActions` methods will be the responsible to set the stores and actions.

The store access continues on the same previous way (toJSON returns a snapshot to the view layer through the props) and the actions access uses the React.js context features (http://jaysoo.ca/2015/06/09/react-contexts-and-dependency-injection/).

_Yes, now the connector also "connect" the actions, why not?_ :grin: 

This approach enhances the portability and makes easy the isomorphism things once all component's ecosystem setup happens on the wrapper/connector component, it also helps to ensure some "bootstrap" pattern.

ToDo:
- update docs
- update tests

### CODE REVIEW

**Comment by samuelsimoes** [comment]
@sobrinho, starting the idea, what do you think?

**Comment by sobrinho** [comment]
I would like to see this as more simpler class:

``` javascript
class ConnectedPersonComponent extends Fluxo.ConnectedComponent {
  constructor () {
    super();

    this.component = PersonComponent;

    this.stores = {
      person: Fluxo.ObjectStore.create(this.props.personInitialData)
    };

    this.actions = {
      person: _.extend(PersonActions, { person: this.stores.person })
    };
  }
}
```

**Comment by samuelsimoes** [comment]
How can we do this keeping the compatibility with no ES6 env or we just ignore this since that everyone that use React gonna use Babel?

**Comment by sobrinho** [comment]
Everyone is using babel somehow (since you need it to compile JSX).

If that case appears, we could do something, but I don't think that is necessary.

**Comment by sobrinho** [comment]
I think we can close that since we moved on.

**Comment by samuelsimoes** [comment]
👍

**Pull request closed without merging**
